name: Add Ticket Link to PR Description

on:
  pull_request:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check Branch Name
        id: check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.payload.pull_request.head.ref
            const match = branchName.match(/(PSK2-\d+|KOKUBAN-\d+)/);
            if (match) {
              const ticketNumber = match[1];
              core.setOutput("ticketUrl", `https://88-oct.atlassian.net/browse/${ticketNumber}`);
              core.setOutput("skip", "false");
            } else {
              core.setOutput("skip", "true");
            }
      - name: Add Ticket Link
        if: ${{ steps.check.outputs.skip != 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prBody = context.payload.pull_request.body;
            const prNumber = context.payload.pull_request.number;
            const ticketLink = `${{ steps.check.outputs.ticketUrl }}`
            console.log(`チケットリンク: ${ticketLink}`);
            
            const updatedPrBody = prBody.replace(/\${Automatically Insert Ticket Link}/, ticketLink);
            
            // PRの本文を更新
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: updatedPrBody
            });
            
